apiVersion: rbac.authorization.k8s.io/v1 
kind: Role 
metadata:
     namespace: roboshop 
     name: sa-reader 
rules: 
- apiGroups: ["*"] # "" indicates the core API group 
  resources: ["*"] # nouns 
  verbs: ["get","watch","list"] # actions 
--- 
apiVersion: rbac.authorization.k8s.io/v1 
# this role binding allows "jane", to read pods in default namespace 
# you have already the role named pod-reader in that namespace 
kind: RoleBinding 
metadata: 
      namespcae: roboshop 
      name: sa-reader 
subjects: 
# you can specify more than one subject 
- kind: ServiceAccount 
  name: roboshop-mysql-secret-reader # name should be case sensitive 
  namespace: roboshop 
roleRef: 
# this role ref specifies the binding to role or cluster role 
- kind: Role # this must be a role or cluster role 
  name: sa-reader # this must watch the name of role or cluster role this wish to bind to 
  apiGroup: rbac.authorization.k8s.io 
--- 
apiVersion: v1 
kind: Pod 
metadata: 
     name: aws-cli 
     namespace: roboshop 
     labels: 
        purpose: sa 
spec: 
   serviceAccount: roboshop-mysql-secret-reader 
   containers: 
   - name: aws-cli 
     image: amazon/aws-cli 
     command: ["sleep","1000"]             